#!/bin/bash
set -e -x

###
# Installing cURL
###
apt-get update
apt-get install -y curl

###
# Downloading chefdk
###
curl -sSlo /resources/chefdk.deb \
  https://packages.chef.io/files/stable/chefdk/${CHEF_VERSION}/ubuntu/14.04/chefdk_${CHEF_VERSION}-1_amd64.deb

###
# Installing chefdk
###
dpkg -i /resources/chefdk.deb

